In [5]:
#Performing Regression using Feed Forward Neural Network

In [6]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [7]:
df = pd.read_csv("flower.xls",header=None)
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
x = df.iloc[:,:-1].astype(float)
x

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [9]:
y = df.iloc[:,-1]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 4, Length: 150, dtype: object

In [10]:
x.shape

(150, 4)

In [11]:
y.shape

(150,)

In [12]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
import keras
import tensorflow as tf

In [14]:
encoded_y = tf.keras.utils.to_categorical(y)
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(x,encoded_y,test_size=0.25,random_state=1)

In [17]:
xtrain.shape

(112, 4)

In [18]:
xtest.shape

(38, 4)

In [19]:
from keras.models import Sequential

In [20]:
from keras.layers import Dense

In [21]:
model = Sequential()

In [22]:
model.add(Dense(8,activation='relu',input_dim=4))
model.add(Dense(6,activation='relu'))
model.add(Dense(3,activation='softmax'))

C:\Users\Hastee\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['mae'])

In [24]:
model.fit(xtrain,ytrain,epochs=100,batch_size=10)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 1.1480 - mae: 0.4523
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0876 - mae: 0.4405 
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0495 - mae: 0.4323 
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0442 - mae: 0.4311 
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0267 - mae: 0.4266 
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0212 - mae: 0.4249 
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9948 - mae: 0.4175 
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9925 - mae: 0.4168 
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9898 - mae: 0.4162
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9557 - mae: 0.4069 
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9347 - mae: 0.4007 
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.9455 - mae: 0.4041 
Epoch 13/100
12/12 ━━━━━━━━

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4569 - mae: 0.2244 
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3933 - mae: 0.1948 
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4002 - mae: 0.2016 
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3897 - mae: 0.1957 
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3938 - mae: 0.1950 
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3581 - mae: 0.1816 
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3824 - mae: 0.1928 
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3850 - mae: 0.1913 
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3984 - mae: 0.1996 
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3642 - mae: 0.1849 
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4229 - mae: 0.2118 
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3598 - mae: 0.1835 
Epoch 83/100
12/12 ━━━━━━━━━━

In [25]:
predictions = model.predict(xtest)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


In [26]:
predictions

array([[9.96335864e-01, 3.01091839e-03, 6.53220166e-04],
       [2.87372410e-01, 6.27437294e-01, 8.51903632e-02],
       [5.98764941e-02, 8.66184354e-01, 7.39392117e-02],
       [9.94749725e-01, 4.26197983e-03, 9.88237560e-04],
       [1.29160702e-01, 4.81422335e-01, 3.89416963e-01],
       [8.17057565e-02, 7.58710563e-01, 1.59583688e-01],
       [1.40390083e-01, 3.39979619e-01, 5.19630313e-01],
       [9.66136217e-01, 2.86626089e-02, 5.20118140e-03],
       [9.52102840e-01, 3.92387547e-02, 8.65845475e-03],
       [1.41404063e-01, 2.45735452e-01, 6.12860501e-01],
       [8.92071500e-02, 7.25176394e-01, 1.85616449e-01],
       [9.88000095e-01, 9.94770508e-03, 2.05212692e-03],
       [1.41404063e-01, 2.45735452e-01, 6.12860501e-01],
       [6.37929663e-02, 8.35584164e-01, 1.00622952e-01],
       [9.75201130e-02, 6.84959471e-01, 2.17520460e-01],
       [9.73898530e-01, 2.07135156e-02, 5.38796792e-03],
       [6.46378919e-02, 8.26962292e-01, 1.08399861e-01],
       [1.09007604e-01, 6.22746

In [27]:
for i in range(1,len(predictions),3):
    print(predictions[i],ytest[i])

[0.2873724  0.6274373  0.08519036] [0. 1. 0.]
[0.1291607  0.48142233 0.38941696] [0. 0. 1.]
[0.9661362  0.02866261 0.00520118] [1. 0. 0.]
[0.08920715 0.7251764  0.18561645] [0. 1. 0.]
[0.06379297 0.83558416 0.10062295] [0. 1. 0.]
[0.06463789 0.8269623  0.10839986] [0. 1. 0.]
[0.98752135 0.00980889 0.00266966] [1. 0. 0.]
[0.11227816 0.60324234 0.2844795 ] [0. 1. 0.]
[0.07175377 0.7997564  0.12848988] [0. 1. 0.]
[0.08668168 0.73673683 0.17658149] [0. 1. 0.]
[0.14140406 0.24573545 0.6128605 ] [0. 0. 1.]
[0.14140406 0.24573545 0.6128605 ] [0. 0. 1.]
[0.9874972  0.00999889 0.00250387] [1. 0. 0.]


In [28]:
y_pred = []

for i in range(0,len(predictions)):
    y_pred.append(np.argmax(predictions[i]))

In [29]:
y_test = []

for i in range(0,len(ytest)):
    y_test.append(np.argmax(ytest[i]))

In [30]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_test,y_pred)

0.9536585365853658